print("Hello World")
print("Hello World")
print("Hello World")
print("Hello World")
print("Hello World")
print("Bye World")

print("Hello World")
print("Hello World")
print("Hello World")
print("Hello World")
print("Hello World")

print("Hello World")
print("Hello World")
print("Hello World")
print("Hello World")
